name: reto_rapicredit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/google_fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/google_fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Barlow
      fonts:
        - asset: assets/google_fonts/Barlow/Barlow-Regular.ttf
        - asset: assets/google_fonts/Barlow/Barlow-Bold.ttf
          weight: 700
    - family: RapicreditIcons
      fonts:
      - asset: assets/rapicredit_fonts/RapicreditIcons/fonts/RapicreditIcons.ttf
